vich_uploader:
    db_driver: orm

    mappings:
        gallery_files:
            uri_prefix: '%app.path.gallery_files%'
            upload_destination: '%kernel.project_dir%/public/%app.path.gallery_files%'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: app_vich_uploader_namer
